### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by htho** [DevExpress/TestCafe-RPC#2]
I like the Idea of testcafe-rpc, but I wonder if it is still compatible with todays testcafe.

**Comment by AndreyBelym** [comment]
I apologize for the delayed response. You can use [Runner API](https://testcafe.io/documentation/402641/reference/testcafe-api/runner) and [Browser Providers API](https://testcafe.io/documentation/402812/guides/extend-testcafe/browser-provider-plugin) in modern TestCafe instead.
